version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - app_network

  laravel_container:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_container:latest
    container_name: laravel_container
    environment:
      - REDIS_HOST=my-redis
    ports:
      - "8000:8000"
    networks:
      - app_network  
    volumes:
      - ./:/var/www/html 

networks:
  app_network:

